export const decklist_brushfire = [
  { name: "Ninetales", set: "Base", quantity: 1 },
  { name: "Weedle", set: "Base", quantity: 4 },
  { name: "Tangela", set: "Base", quantity: 2 },
  { name: "Nidoran ♂", set: "Base", quantity: 4 },
  { name: "Arcanine", set: "Base", quantity: 1 },
  { name: "Growlithe", set: "Base", quantity: 2 },
  { name: "Charmeleon", set: "Base", quantity: 2 },
  { name: "Vulpix", set: "Base", quantity: 2 },
  { name: "Charmander", set: "Base", quantity: 4 },
  { name: "Lass", set: "Base", quantity: 1 },
  { name: "PlusPower", set: "Base", quantity: 1 },
  { name: "Energy Retrieval", set: "Base", quantity: 2 },
  { name: "Switch", set: "Base", quantity: 1 },
  { name: "Potion", set: "Base", quantity: 3 },
  { name: "Gust of Wind", set: "Base", quantity: 1 },
  { name: "Energy Removal", set: "Base", quantity: 1 },
  { name: "Grass Energy", set: "Base", quantity: 10 },
  { name: "Fire Energy", set: "Base", quantity: 18 },
];
