export const decklist_brushfire = [
  { name: 'Ninetales', set: 'Base', quantity: 1 },
  { name: 'Weedle', set: 'Base', quantity: 4 },
  { name: 'Tangela', set: 'Base', quantity: 2 },
  { name: 'Nidoran ♂', set: 'Base', quantity: 4 },
  { name: 'Arcanine', set: 'Base', quantity: 1 },
  { name: 'Growlithe', set: 'Base', quantity: 2 },
  { name: 'Charmeleon', set: 'Base', quantity: 2 },
  { name: 'Vulpix', set: 'Base', quantity: 2 },
  { name: 'Charmander', set: 'Base', quantity: 4 },
  { name: 'Lass', set: 'Base', quantity: 1 },
  { name: 'PlusPower', set: 'Base', quantity: 1 },
  { name: 'Energy Retrieval', set: 'Base', quantity: 2 },
  { name: 'Switch', set: 'Base', quantity: 1 },
  { name: 'Potion', set: 'Base', quantity: 3 },
  { name: 'Gust of Wind', set: 'Base', quantity: 1 },
  { name: 'Energy Removal', set: 'Base', quantity: 1 },
  { name: 'Grass Energy', set: 'Base', quantity: 10 },
  { name: 'Fire Energy', set: 'Base', quantity: 18 },
];

export const decklist_overgrowth = [
  { name: 'Gyarados', set: 'Base', quantity: 1 },
  { name: 'Magikarp', set: 'Base', quantity: 2 },
  { name: 'Starmie', set: 'Base', quantity: 3 },
  { name: 'Staryu', set: 'Base', quantity: 4 },
  { name: 'Beedrill', set: 'Base', quantity: 1 },
  { name: 'Kakuna', set: 'Base', quantity: 2 },
  { name: 'Ivysaur', set: 'Base', quantity: 2 },
  { name: 'Weedle', set: 'Base', quantity: 4 },
  { name: 'Bulbasaur', set: 'Base', quantity: 4 },
  { name: 'Potion', set: 'Base', quantity: 1 },
  { name: 'Bill', set: 'Base', quantity: 2 },
  { name: 'Super Potion', set: 'Base', quantity: 2 },
  { name: 'Switch', set: 'Base', quantity: 2 },
  { name: 'Gust of Wind', set: 'Base', quantity: 2 },
  { name: 'Potion', set: 'Base', quantity: 12 },
  { name: 'Water Energy', set: 'Base', quantity: 12 },
  { name: 'Grass Energy', set: 'Base', quantity: 16 },
];

export const decklist_zap = [
  // { name: 'Mewtwo', set: 'Base', quantity: 1 },
  // { name: 'Kadabra', set: 'Base', quantity: 1 },
  // { name: 'Jynx', set: 'Base', quantity: 2 },
  // { name: 'Haunter', set: 'Base', quantity: 2 },
  // { name: 'Gastly', set: 'Base', quantity: 3 },
  // { name: 'Drowzee', set: 'Base', quantity: 2 },
  // { name: 'Abra', set: 'Base', quantity: 3 },
  { name: 'Pikachu', set: 'Base', quantity: 4 },
  // { name: 'Magnemite', set: 'Base', quantity: 3 },
  // { name: 'Computer Search', set: 'Base', quantity: 1 },
  // { name: 'Defender', set: 'Base', quantity: 1 },
  // { name: 'Super Potion', set: 'Base', quantity: 1 },
  // { name: 'Professor Oak', set: 'Base', quantity: 1 },
  // { name: 'Switch', set: 'Base', quantity: 2 },
  // { name: 'Potion', set: 'Base', quantity: 1 },
  // { name: 'Gust of Wind', set: 'Base', quantity: 2 },
  // { name: 'Bill', set: 'Base', quantity: 2 },
  { name: 'Lightning Energy', set: 'Base', quantity: 12 },
  // { name: 'Psychic Energy', set: 'Base', quantity: 16 },
];

export const decklist_blackout = [
  { name: 'Hitmonchan', set: 'Base', quantity: 1 },
  { name: "Farfetch'd", set: 'Base', quantity: 2 },
  { name: 'Wartortle', set: 'Base', quantity: 2 },
  { name: 'Squirtle', set: 'Base', quantity: 4 },
  { name: 'Staryu', set: 'Base', quantity: 3 },
  { name: 'Onix', set: 'Base', quantity: 3 },
  { name: 'Sandshrew', set: 'Base', quantity: 3 },
  { name: 'Machoke', set: 'Base', quantity: 2 },
  { name: 'Machop', set: 'Base', quantity: 4 },
  { name: 'Super Energy Removal', set: 'Base', quantity: 1 },
  { name: 'PlusPower', set: 'Base', quantity: 1 },
  { name: 'Professor Oak', set: 'Base', quantity: 1 },
  { name: 'Gust of Wind', set: 'Base', quantity: 1 },
  { name: 'Energy Removal', set: 'Base', quantity: 4 },
  { name: 'Fighting Energy', set: 'Base', quantity: 16 },
  { name: 'Water Energy', set: 'Base', quantity: 12 },
];
